theme: jekyll-theme-minimal
title: Chrissie Faenza
description: Hello! My name is Chrissie Faenza, and I'm a rising junior at Lehigh University, in Bethlehem, Pennsylvania. I'm studying Journalism, with double minors in Marketing and Business. 
